### ISSUE TITLE
what is a sample checkrole.yml like?

### ISSUE THREAD

**Issue by freshyuan** [red-hat-storage/cockpit-ceph-installer#6]
hi,
every time when I probe hosts , I got the error below, I have no idea what is a sample checkrole.yml like，could you please give me a sample?
`2019-05-19 19:32:54,551 - werkzeug - INFO - 127.0.0.1 - - [19/May/2019 19:32:54] "GET /api/v1/jobs/d7bfd752-7a29-11e9-b204-920c1284bdf7/events?task=CEPH_CHECK_ROLE HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib64/python2.7/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib64/python2.7/site-packages/flask_restful/__init__.py", line 266, in error_router
    return self.handle_error(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib64/python2.7/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib64/python2.7/site-packages/flask_restful/__init__.py", line 266, in error_router
    return self.handle_error(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib64/python2.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/root/ansible-runner-service-master/runner_service/controllers/utils.py", line 49, in decorated
    return f(*args, **kwargs)
  File "/root/ansible-runner-service-master/runner_service/controllers/utils.py", line 118, in wrapper
    return f(*args, **kwargs)
  File "/root/ansible-runner-service-master/runner_service/controllers/jobs.py", line 84, in get
    response = get_events(play_uuid, filter)
  File "/root/ansible-runner-service-master/runner_service/services/jobs.py", line 158, in get_events
    matched_events[event_filename] = event_summary(event_info)
  File "/root/ansible-runner-service-master/runner_service/services/jobs.py", line 104, in event_summary
    event_data = {k: event_info['event_data'][k] for k in summary_keys
  File "/root/ansible-runner-service-master/runner_service/services/jobs.py", line 105, in <dictcomp>
    if k in event_info.get('event_data')}
TypeError: argument of type 'NoneType' is not iterable
2019-05-19 19:32:55,340 - runner_service.services.playbook - INFO - Playbook checkrole.yml, UUID=d7bfd752-7a29-11e9-b204-920c1284bdf7 ended, status=failed
2019-05-19 19:32:55,343 - runner_service.services.playbook - INFO - Playbook checkrole.yml Stats: None
2019-05-19 19:32:55,343 - runner_service.services.playbook - DEBUG - Dropping runner object from runner_cache`

**Comment by pcuzner** [comment]
checkrole is here - https://github.com/pcuzner/ceph-check-role

I'm hoping to get it merged into ceph ansible. However, your question does highlight th fact that I;m not checking that the required playbooks are in place. I'll raise a separate issue to track that

**Comment by freshyuan** [comment]
I tried four version of checkrole as follows. all of them raise the same error...
1. 
- name: Validate hosts against desired cluster state
  hosts: all
  gather_facts: false
  vars:
    inventory:
      node-1:
        mons,osds
      node-2:
        mons,osds
      node-3:
        mons,osds

  tasks:
 
    - name: CEPH_CHECK_ROLE
      ceph_check_role:
        role: "{{ inventory[inventory_hostname] }}"
        mode: prod
        deployment: rpm
        flashusage: journal
        osdtype: bluestore

2.
- name: Validate hosts against desired cluster state
  hosts: all
  gather_facts: false
  tasks:
 
    - name: CEPH_CHECK_ROLE
      ceph_check_role:
        role: "{{ inventory[inventory_hostname] }}"
        mode: prod
        deployment: rpm
        flashusage: journal
        osdtype: bluestore

3. 
- name: Validate hosts against desired cluster state
  hosts: all
  become: true
  gather_facts: false

  tasks:

    - name: CEPH_CHECK_ROLE
      ceph_check_role:
        mode: dev
        deployment: rpm

4. 
tasks:
    - name: CEPH_CHECK_ROLE
      ceph_check_role:
        role: "{{ inventory[inventory_hostname] }}"
        mode: dev
        deployment: rpm
      register: result

**Comment by pcuzner** [comment]
If you're running check role from the UI - this is what the checkrole playbook should look like
```
---

# check host role

- name: Validate hosts against desired cluster state
  hosts: all
  become: true
  gather_facts: false

  tasks:
 
    - name: CEPH_CHECK_ROLE
      ceph_check_role:
        role: "{{ inventory[inventory_hostname]|default ('undefined') }}"
        mode: "{{ mode }}"
        deployment: "{{ deployment }}"
        flashusage: "{{ flashusage }}"
        osdtype: "{{ osdtype }}"
```

On the other hand, if you want to run it manually
```
---

# check host role

- name: Validate hosts against desired cluster state
  hosts: all
  become: true
  gather_facts: false
  vars:
    inventory:
      nautilus-1: osds,mons
      nautilus-2: osds,mons
      nautilus-3: osds,mons
    mode: dev
    deployment: container 
    flashusage: journal
    osdtype: bluestore
  tasks:
 
    - name: CEPH_CHECK_ROLE
      ceph_check_role:
        role: "{{ inventory[inventory_hostname]|default ('undefined') }}"
        mode: "{{ mode }}"
        deployment: "{{ deployment }}"
        flashusage: "{{ flashusage }}"
        osdtype: "{{ osdtype }}"
```
@freshyuan does that help?
