### ISSUE TITLE
Task: fail on unsupported ansible version( Ansible version must be 2.9!)

### ISSUE THREAD

**Issue by imoyao** [red-hat-storage/cockpit-ceph-installer#63]
hello? Has anyone encountered this problem?

![image](https://user-images.githubusercontent.com/22978431/81249902-5cfca280-9052-11ea-8100-dbd956354e96.png)

content of check_system.yml:
`vi /usr/share/ceph-ansible/roles/ceph-validate/tasks/check_system.yml +7`
```
---
- name: fail on unsupported ansible version (1.X)
  fail:
    msg: "Ansible version must be >= 2.x, please update!"
  when: ansible_version.major|int < 2

- name: fail on unsupported ansible version
  fail:
---
- name: fail on unsupported ansible version (1.X)
  fail:
    msg: "Ansible version must be >= 2.x, please update!"
  when: ansible_version.major|int < 2

- name: fail on unsupported ansible version
  fail:
    msg: "Ansible version must be 2.9!"
  when: ansible_version.minor|int != 9

- name: fail on unsupported system
  fail:
    msg: "System not supported {{ ansible_system }}"
  when: ansible_system not in ['Linux']

---
- name: fail on unsupported ansible version (1.X)
  fail:
    msg: "Ansible version must be >= 2.x, please update!"
  when: ansible_version.major|int < 2

- name: fail on unsupported ansible version
  fail:
    msg: "Ansible version must be 2.9!"
  when: ansible_version.minor|int != 9

- name: fail on unsupported system
  fail:
    msg: "System not supported {{ ansible_system }}"
  when: ansible_system not in ['Linux']

- name: fail on unsupported architecture
  fail:
    msg: "Architecture not supported {{ ansible_architecture }}"
  when: ansible_architecture not in ['x86_64', 'ppc64le', 'armv7l', 'aarch64']

- name: fail on unsupported distribution
  fail:
    msg: "Distribution not supported {{ ansible_os_family }}"
  when: ansible_os_family not in ['Debian', 'RedHat', 'ClearLinux', 'Suse']

- name: fail on unsupported CentOS release
  fail:
    msg: "CentOS release not supported {{ ansible_distribution_major_version }} with dashboard"
  when:
    - ansible_distribution == 'CentOS'
```
Here is my device information:
```
[root@cephnode1 cockpit-ceph-installer]# cat /etc/redhat-release 
CentOS Linux release 7.7.1908 (Core)
[root@cephnode1 cockpit-ceph-installer]# uname -a
Linux cephnode1 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[root@cephnode1 cockpit-ceph-installer]# rpm -qa|grep ansible
ansible-2.9.7-1.el7.noarch
```

**Comment by msLinuxNinja** [comment]
Same here, except on Centos8.1
```
[root@ceph1 utils]# ansible --version
ansible 2.9.7
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
```

**Comment by msLinuxNinja** [comment]
Managed to get past this by installing Ansible 2.9 on the ceph nodes: `pip3 install -Iv ansible==2.9`

**Comment by msLinuxNinja** [comment]
I see it would've failed either way next:
```yml
- name: fail on unsupported CentOS release
  fail:
    msg: "CentOS release not supported {{ ansible_distribution_major_version }} with dashboard"
  when:
    - ansible_distribution == 'CentOS'
    - ansible_distribution_major_version | int == 7
    - not containerized_deployment | bool
    - dashboard_enabled | bool
```
